### ISSUE TITLE
excellent project!! but I have a problem with "dotenv" 

### ISSUE THREAD

**Issue by chobbong** [Sven-Bo/streamlit-income-expense-tracker#1]
hello! Sven-Bo! 
I am one of your avid fans. 
I tried to clone your code, I had a problem with 'dotenv'. It seemed that there was an issue within 'dotenv' itself. Even when I ran the app, the data was not updated in deta, and although I included dotenv in the requirements.txt, when I uploaded the APP to streamlit, it says 'dotenv' is a no module. I even tried uploading the KEY value to loadenv itself, but it doesn't work. I'm not sure what to do. I would appreciate your help!

**Comment by Sven-Bo** [comment]
@chobbong Thanks for the feedback! To fix the issue, make sure dotenv is set up on the Streamlit Cloud using requirements.txt. Keep in mind that Deta Cloud has changed to Deta Space, so the data commands in the video our outdated.
If possible, could you please put your next question(s) under the related YouTube video? It'll help others who might have the same problem. Thanks!
